### PR TITLE
Vary libcaf_openmp procedure prefix; add test

### PR DESCRIPTION
**Pull request by rouson**
@jerryd Let's discuss this via phone or hangouts before merging.  I think I might have hit a major roadblock.  We are either going to require some minor surgery in the compiler to get this to work or we'll need source transformation to create the OpenMP parallel region in the main program before the compiler sees it.  A source transformation capability exists on the [caffeinate-opencoarrays](https://github.com/jerryd/opencoarrays/tree/caffeinate-opencoarrays) branch so we can repurpose it for this and I think we should do that (or do the required surgery on the compiler to obviate the need for source transformation) before proceeding.

### CODE REVIEW

**Comment by jerryd** [comment]
@rouson In the hello.f90, is it necessary to 'use omp' since this is be done in the library implementation file.

**Comment by rouson** [comment]
@jerryd Great catch!  I removed the unnecessary use statement and pushed a new commit that now shows in this thread.  If there are no other issues, one of us can merge and close this pull request and deleted the vary-prefix branch.  Then our main task is evaluating whether to proceed with modifying
the compiler front-end or using source transformation.  Let me know what you find out about the former
and I'll let you know what I find out about the former.

**Comment by jerryd** [comment]
Looks good, merging

**Comment by rouson** [comment]
Thanks.  I just deleted the branch.

**Pull request merged**
